// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDj8b9iEtiskM_iQ-UF9J6Ow-aQjqob1IM',
    appId: '1:629634382533:web:758f68b433a295cf620eac',
    messagingSenderId: '629634382533',
    projectId: 'notes-31b04',
    authDomain: 'notes-31b04.firebaseapp.com',
    databaseURL: 'https://notes-31b04-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'notes-31b04.appspot.com',
    measurementId: 'G-NE1J1FVZXC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDerR7dM_Ag4kxrUwgi9IKZj6tYv3U7cu0',
    appId: '1:629634382533:android:f6346907bae84103620eac',
    messagingSenderId: '629634382533',
    projectId: 'notes-31b04',
    databaseURL: 'https://notes-31b04-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'notes-31b04.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyASHx3A9I1neIoFK0JUD7FyR_yZ_LrAEDc',
    appId: '1:629634382533:ios:ffa7eeedef65852c620eac',
    messagingSenderId: '629634382533',
    projectId: 'notes-31b04',
    databaseURL: 'https://notes-31b04-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'notes-31b04.appspot.com',
    iosBundleId: 'com.example.notesFirestore',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyASHx3A9I1neIoFK0JUD7FyR_yZ_LrAEDc',
    appId: '1:629634382533:ios:ffa7eeedef65852c620eac',
    messagingSenderId: '629634382533',
    projectId: 'notes-31b04',
    databaseURL: 'https://notes-31b04-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'notes-31b04.appspot.com',
    iosBundleId: 'com.example.notesFirestore',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDj8b9iEtiskM_iQ-UF9J6Ow-aQjqob1IM',
    appId: '1:629634382533:web:d97cc3176ed3798a620eac',
    messagingSenderId: '629634382533',
    projectId: 'notes-31b04',
    authDomain: 'notes-31b04.firebaseapp.com',
    databaseURL: 'https://notes-31b04-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'notes-31b04.appspot.com',
    measurementId: 'G-559T8V71B1',
  );

}